services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6380:6380"
    expose:
      - "6380"
      - elevator_network
    command: --port 6380

  server:
    depends_on:
      - redis
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    command: |
      npm start
    container_name: server
    environment:
      - DB_URL=${DB_URL:?variable DB_URL is missing}
      - ISSUER_BASE_URL=${ISSUER_BASE_URL:?variable ISSUER_BASE_URL is missing}
      - TEST_USER_TOKEN=${TEST_USER_TOKEN:?variable TEST_USER_TOKEN is missing}
      - REDIS_URL=${REDIS_URL:?variable REDIS_URL is missing}
    ports:
      - "3000:3000"
    networks:
      - elevator_network
  
  client:
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    command: "npx http-server ./dist -p 4243"
    container_name: client
    ports:
      - "4243:4243"
    depends_on:
      - server
    networks:
      - elevator_network

networks:
  elevator_network:
