services:
  server:
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    command: |
      npm start
    container_name: server
    ports:
      - "3000:3000"
    networks:
      - elevator_network
  
  client:
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    command: "npx http-server ./dist -p 4242"
    container_name: client
    ports:
      - "4242:4242"
    depends_on:
      - server
    networks:
      - elevator_network

networks:
  elevator_network:
