version: '3.8'

services:
  server:
    environment:
      - NODE_ENV=production

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "443:4242"
    environment:
      - NODE_ENV=production